### ISSUE TITLE
expose directory service port

### ISSUE THREAD

**Issue by NodeGuy** [vpetersson/docker-torrelay#1]
> The container is also configured to listen on port 9001 for the relay traffic, and 9030 for the directory service.

Should you be exposing 9030 in the Dockerfile?

**Comment by vpetersson** [comment]
Actually, I just forgot to update the README to reflect that. The directory service automatically gets disabled if you use any of the bandwidth accounting (which I do). 

Will update the README and Dockerfile to reflect that.
